# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a4925006bb9d0e345149762088f2051e0dfe081f5f73dff08e530890a07e879f0611c38d5865714f67d28dcdbc1dfef854128558ef38d046846508be7a1c38

test:
  secret_key_base: ce5249e9ee04b9b20e048f4faf2fdcc0f97d72224c11e3bf30426e513378af52b03d0c9ff4b640e6f0800e6527aaf63b47cce9f05502248da777f412bd903f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
